project_id = "databro"

[functions.ask-data-dev]
verify_jwt = false

[functions.ask-data-prod]
verify_jwt = false

[functions.ask-prescription-dev]
verify_jwt = false

[functions.ask-prescription-prod]
verify_jwt = false
