name: Build and Push API Gateway

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
    paths:
      - "services/api_gateway/**"
      - ".github/workflows/build-api-gateway.yml"
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          fi

      - name: Azure Login
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
          az account set -s ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name databro${{ env.ENV_NAME }}acr

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/api_gateway
          push: true
          tags: databro${{ env.ENV_NAME }}acr.azurecr.io/api-gateway:latest

      - name: Restart Container App
        run: |
           az containerapp revision copy \
            --name api-gateway \
            --resource-group databro-${{ env.ENV_NAME }}-rg \
            --image databro${{ env.ENV_NAME }}acr.azurecr.io/api-gateway:latest
